import { ReactNode } from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header, Providers } from '@/components';
import {
    ClerkProvider,

} from '@clerk/nextjs'

import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <ClerkProvider>
          <html lang="en">
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <Header />
          <main className={'p-4'}>
              <div className={'bg-white rounded-2xl shadow-2xl p-8 '}>
                  <Providers>
                      {children}
                  </Providers>
              </div>
          </main>
          </body>
          </html>
      </ClerkProvider>

  );
}
