import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Header, Providers } from '@/components';
import { getCarts, revalidateRootPage  } from '@/app/cart/actions'
import {getUser} from "@/app/(auth)/actions";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cartData = await getCarts();
    const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header
          revalidateRootPage={revalidateRootPage}
          user={user}
          cartAmount={cartData.carts.reduce((acc, cur) => acc + cur.quantity , 0) ?? 0}/>
      <main className={'p-4'}>
          <div className={'bg-white rounded-2xl shadow-2xl p-8 '}>
              <Providers>
                  {children}
              </Providers>
          </div>
      </main>
      </body>
    </html>
  );
}
